### ISSUE TITLE
Misuse of Python language feature

### ISSUE THREAD

**Issue by jmgnc** [oasis-open/cti-pattern-validator#32]
In looking at the code to do my own implementation, I noticed the misuse of the double underscore (__) in the code base.  The code here: https://github.com/oasis-open/cti-pattern-matcher/blob/master/stix2matcher/matcher.py#L2125 accesses self.__parse_tree.  This "should" not work, as the double underscore is intended to prevent two different classes from stepping on each other: https://docs.python.org/2/tutorial/classes.html#private-variables-and-class-local-references  This happens to work because both classes are named Pattern, even though it should not, as they are unrelated classes.  The issue is at the assignment: https://github.com/oasis-open/cti-pattern-validator/blob/master/stix2patterns/pattern.py#L34

There should probably be a method added to the stix2patterns.pattern.Pattern class that accepts and object, and calls antlr4.ParseTreeWalker.DEFAULT.walk w/ the object and __parse_tree. 
 __parse_tree should be renamed to _parse_tree as that is a more common method of denoting non-public attributes and methods.

**Comment by gtback** [comment]
Thanks, @jmgnc. Good catch!

Any chance you'd like to submit a PR to fix this? 😉

**Comment by jmgnc** [comment]
I'd love to, but we are still unable to sign the CLA.  I'm checking on what the latest status is.

The easiest thing is to replace all the double underscores w/ single, but as there are other parts of the code base, it will require significant testing to make sure it doesn't break other parts of the code.

**Comment by chisholm** [comment]
If you add a walk method to stix2patterns.pattern.Pattern, __parse_tree could remain private.  It seems reasonable to regard the parse tree as internal, especially if the walker method is made public.  Having a walker method might make sense, as both inspection and matching basically work the same way: walking the parse tree.  Making it public makes sense if we think others might want to write their own listeners to do their own things with patterns.  But I think the idea has been to make simple APIs and shield people from the complexities of antlr.  Do we think people might want to write their own listeners?

To me, the difference between __foo and _foo is more than convention.  To me, they mean different things.  I am used to at least three different access levels: public, private, protected (Java, for example, has one more).  __foo indicates private; _foo is the convention meaning protected; and foo is public.  If I really want a keep-out sign on a property, I put two underscores on it.  I just messed up __parse_tree (but also note that stix2patterns.pattern.Pattern was written before stix2matcher.matcher.Pattern existed, so private access made sense at the time).

**Comment by gtback** [comment]
I don't think it's fair to say `stix2patterns.pattern.Pattern` and `stix2matcher.matcher.Pattern` are *unrelated* (the former subclasses the latter), but indeed this only works because the actual classes have the same name and `__parse_tree` gets mangled to `_Pattern__parse_tree`.

As @chisholm points out, there are two decent solutions: convert `__parse_tree` to `_parse_tree` (effectively making it "protected" rather than "private"), or leaving it private and exposing a public (or protected) `walk()` method. (We could also expose a "readonly" attribute using a public `@property` getter but no equivalent `@setter`). I guess I would be tempted to lean towards a `walk()` method, even though I don't necessarily see anyone else writing any custom listeners right now, unless they potentially want to expand on the functionality provided by the inspector.

**Comment by jmgnc** [comment]
Yeah, I'm fine w/ leaving __, as long as the other class is fixed so that it doesn't depend upon it having the same name to access it.

I ran across this because I started doing my own translator.  I looked at the existing work, and didn't see an easy way to either get an AST, or a clean interface to the parser.  I do agree that there aren't going to be many other listeners.

**Comment by gtback** [comment]
This has been fixed, and the matcher has been updated to use the new version of this library.
